# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/scalp_zynqps_system_ila_0_0.xci
# IP: The module: 'scalp_zynqps_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/bd_c0d9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c0d9 || ORIG_REF_NAME==bd_c0d9} -quiet] -quiet

# IP: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/ip/ip_0/bd_c0d9_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c0d9_ila_lib_0 || ORIG_REF_NAME==bd_c0d9_ila_lib_0} -quiet] -quiet

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c0d9_ila_lib_0 || ORIG_REF_NAME==bd_c0d9_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c0d9_ila_lib_0 || ORIG_REF_NAME==bd_c0d9_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/ip/ip_0/bd_c0d9_ila_lib_0_ooc.xdc

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/bd_c0d9_ooc.xdc

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/scalp_zynqps_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalp_zynqps_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/scalp_zynqps_system_ila_0_0.xci
# IP: The module: 'scalp_zynqps_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/bd_c0d9.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c0d9 || ORIG_REF_NAME==bd_c0d9} -quiet] -quiet

# IP: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/ip/ip_0/bd_c0d9_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c0d9_ila_lib_0 || ORIG_REF_NAME==bd_c0d9_ila_lib_0} -quiet] -quiet

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c0d9_ila_lib_0 || ORIG_REF_NAME==bd_c0d9_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c0d9_ila_lib_0 || ORIG_REF_NAME==bd_c0d9_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/ip/ip_0/bd_c0d9_ila_lib_0_ooc.xdc

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/bd_0/bd_c0d9_ooc.xdc

# XDC: c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_system_ila_0_0/scalp_zynqps_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scalp_zynqps_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
