# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z015clg485-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    set rt::enableVHDL2008 1
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/bd/vga_hdmi_clk_rst_system_inst_0/ipshared/3cbc
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/814a/hdl/verilog
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/1017/hdl/verilog
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/52c0/hdl/verilog
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/2276/hdl/verilog
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/3cbc
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/ec67/hdl
    C:/CochetLPSC/scalp_revc_windows/scalp_zynqps/bd/vga_hdmi_clk_rst_system_inst_0
  } {
      C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/bd/vga_hdmi_clk_rst_system_inst_0/ipshared/3cbc
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/814a/hdl/verilog
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/1017/hdl/verilog
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/52c0/hdl/verilog
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/2276/hdl/verilog
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/3cbc
    c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/ec67/hdl
    C:/CochetLPSC/scalp_revc_windows/scalp_zynqps/bd/vga_hdmi_clk_rst_system_inst_0
  } {
      c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v
      c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_gnd_constant_0/synth/scalp_zynqps_gnd_constant_0.v
      c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v
      c:/CochetLPSC/scalp_revc_windows/scalp_zynqps/ip/scalp_zynqps_xlconcat_0_0/synth/scalp_zynqps_xlconcat_0_0.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/vga_hdmi_clk_rst_system_inst_0_vga_hdmi_clock_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/vga_hdmi_clk_rst_system_inst_0_rst_ps7_1_vga_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/vga_hdmi_clk_rst_system_inst_0_rst_ps7_2_hdmi_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_processing_system7_0_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_scalp_axi_link_firmwareid_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_axi_gpio_switches_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_axi_intc_0_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_axi_gpio_reset_btn_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_system_ila_0_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_scalp_axi_link_cplx_num_regs_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_rst_ps7_0_125M_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_sys_clock_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_axi_iic_ioext_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_axi_gpio_joystick_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_ps7_0_axi_periph_upgraded_ipi_imp_xbar_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/realtime/scalp_zynqps_ps7_0_axi_periph_imp_auto_pc_0_stub.vhdl
      C:/CochetLPSC/scalp_revc_windows/scalp_zynqps/bd/vga_hdmi_clk_rst_system_inst_0/synth/vga_hdmi_clk_rst_system_inst_0.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_zynqps/synth/scalp_zynqps.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -vhdl2008 -lib scalp_lib {
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/scalp_axi_pkg.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/scalp_hdmi_pkg.vhd
    }
      rt::read_vhdl -vhdl2008 -lib xil_defaultlib {
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/scalp_cplx_num_regs.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/scalp_firmwareid.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/vga_stripes.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/vga_controler.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/vga.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/tmds_encoder.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/serializer_10_to_1.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/vga_to_hdmi.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/scalp_hdmi.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/scalp_pwm.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/scalp_zynqps_user.vhd
      C:/CochetLPSC/scalp_revc_windows/scalp_user_design/scalp_user_design.srcs/sources_1/imports/files/scalp_user_design.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top scalp_user_design
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/CochetLPSC/scalp_revc_windows/scalp_user_design/.Xil/Vivado-24232-Torchet/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
